'use strict';

module.exports = {
	async up(queryInterface, Sequelize) {
		await queryInterface.bulkInsert('role', [
			{
				title: 'president',
				description: null,
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				title: 'manager',
				description: null,
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				title: 'leader',
				description: null,
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				title: 'staff',
				description: null,
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				title: 'customer',
				description: null,
				createdAt: new Date(),
				updatedAt: new Date(),
			},
		]);

		await queryInterface.bulkInsert('permission', [
      {
        method: 'GET',
        resource: 'office',
        description: null,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        method: 'POST',
        resource: 'office',
        description: null,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        method: 'PUT',
        resource: 'office',
        description: null,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        method: 'PATCH',
        resource: 'office',
        description: null,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        method: 'DELETE',
        resource: 'office',
        description: null,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        method: 'GET',
        resource: 'employee',
        description: null,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        method: 'POST',
        resource: 'employee',
        description: null,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        method: 'PUT',
        resource: 'employee',
        description: null,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        method: 'PATCH',
        resource: 'employee',
        description: null,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        method: 'DELETE',
        resource: 'employee',
        description: null,
        createdAt: new Date(),
				updatedAt: new Date(),
      }
    ]);

    await queryInterface.bulkInsert('role_permission', [
      {
        roleId: 1,
        permissionId: 1,
        active: true,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 1,
        permissionId: 2,
        active: true,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 1,
        permissionId: 3,
        active: true,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 1,
        permissionId: 4,
        active: true,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 1,
        permissionId: 5,
        active: true,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 1,
        permissionId: 6,
        active: true,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 1,
        permissionId: 7,
        active: true,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 1,
        permissionId: 8,
        active: true,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 1,
        permissionId: 9,
        active: true,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 1,
        permissionId: 10,
        active: true,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 2,
        permissionId: 1,
        active: true,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 2,
        permissionId: 2,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 2,
        permissionId: 3,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 2,
        permissionId: 4,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 2,
        permissionId: 5,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 2,
        permissionId: 6,
        active: true,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 2,
        permissionId: 7,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 2,
        permissionId: 8,
        active: true,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 2,
        permissionId: 9,
        active: true,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 2,
        permissionId: 10,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 3,
        permissionId: 1,
        active: true,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 3,
        permissionId: 2,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 3,
        permissionId: 3,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 3,
        permissionId: 4,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 3,
        permissionId: 5,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 3,
        permissionId: 6,
        active: true,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 3,
        permissionId: 7,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 3,
        permissionId: 8,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 3,
        permissionId: 9,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 3,
        permissionId: 10,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 4,
        permissionId: 1,
        active: true,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 4,
        permissionId: 2,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 4,
        permissionId: 3,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 4,
        permissionId: 4,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 4,
        permissionId: 5,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 4,
        permissionId: 6,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 4,
        permissionId: 7,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 4,
        permissionId: 8,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 4,
        permissionId: 9,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 4,
        permissionId: 10,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 5,
        permissionId: 1,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 5,
        permissionId: 2,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 5,
        permissionId: 3,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 5,
        permissionId: 4,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 5,
        permissionId: 5,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 5,
        permissionId: 6,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 5,
        permissionId: 7,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 5,
        permissionId: 8,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 5,
        permissionId: 9,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
      {
        roleId: 5,
        permissionId: 10,
        active: false,
        createdAt: new Date(),
				updatedAt: new Date(),
      },
    ])
	},

	async down(queryInterface, Sequelize) {
		await queryInterface.bulkDelete('role_permission', null, {});
    await queryInterface.bulkDelete('role', null, {});
    await queryInterface.bulkDelete('permission', null, {});
	},
};
